<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_oauth_server.create_client_command' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/oauth-server-bundle/Command/CreateClientCommand.php';

return $this->services['fos_oauth_server.create_client_command'] = new \FOS\OAuthServerBundle\Command\CreateClientCommand(${($_ = isset($this->services['fos_oauth_server.client_manager.default']) ? $this->services['fos_oauth_server.client_manager.default'] : $this->load('getFosOauthServer_ClientManager_DefaultService.php')) && false ?: '_'});
