<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container12honkg\appProdDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container12honkg/appProdDebugProjectContainer.php') {
    touch(__DIR__.'/Container12honkg.legacy');

    return;
}

if (!\class_exists(appProdDebugProjectContainer::class, false)) {
    \class_alias(\Container12honkg\appProdDebugProjectContainer::class, appProdDebugProjectContainer::class, false);
}

return new \Container12honkg\appProdDebugProjectContainer(array(
    'container.build_hash' => '12honkg',
    'container.build_id' => 'd9f859b6',
    'container.build_time' => 1553172848,
), __DIR__.\DIRECTORY_SEPARATOR.'Container12honkg');
