<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOuttsxr\appProdDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOuttsxr/appProdDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerOuttsxr.legacy');

    return;
}

if (!\class_exists(appProdDebugProjectContainer::class, false)) {
    \class_alias(\ContainerOuttsxr\appProdDebugProjectContainer::class, appProdDebugProjectContainer::class, false);
}

return new \ContainerOuttsxr\appProdDebugProjectContainer([
    'container.build_hash' => 'Outtsxr',
    'container.build_id' => 'a034bb46',
    'container.build_time' => 1553865271,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOuttsxr');
