<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKmx5tvr\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKmx5tvr/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKmx5tvr.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKmx5tvr\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerKmx5tvr\appDevDebugProjectContainer([
    'container.build_hash' => 'Kmx5tvr',
    'container.build_id' => '74162cec',
    'container.build_time' => 1553864293,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKmx5tvr');
