<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAliqsoa\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAliqsoa/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerAliqsoa.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerAliqsoa\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerAliqsoa\appDevDebugProjectContainer([
    'container.build_hash' => 'Aliqsoa',
    'container.build_id' => 'e71098c8',
    'container.build_time' => 1558599617,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAliqsoa');
